/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Panel extends javax.swing.JPanel
{

    JButton boton = new JButton();
    JLabel texto = new JLabel();
    
    Color colorFondo = new Color(76, 171, 133);
    Font fuente=new Font("Arial", Font.BOLD, 35);
    
    int ancho = 640;
    int alto = 480;
    Image banner;

    public Panel()
    {
        initComponents();
        
        banner = new ImageIcon(getClass().getResource("/Sources/banner.png")).getImage();
        
        texto.setFont(fuente);
        texto.setText("DAVUELTASPUTO");
        texto.setLocation(ancho/2-140, 15);
        texto.setSize(360, 40);

        setSize(ancho, alto);
        boton.setSize(180, 40);
        boton.setLocation((ancho / 2) - 90, alto / 2 - 80);
        this.setBackground(colorFondo);
        boton.setBackground(Color.yellow);
        boton.setText("INGRESAR COMPRA");
        boton.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent me)
            {
                JOptionPane.showMessageDialog(null, "Compra registrada");
            }

        });
        this.add(texto);
        this.add(boton);
    }

//    @Override
//    protected void paintComponent(Graphics g)
//    {
//        g.drawImage(banner, 0, 0, this);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
